### ISSUE TITLE
Write finish_by_hand test

### ISSUE THREAD

**Issue by niharikasingh** [knod/docassemble-juvenilesealing#29]
`tests/features/finish_by_hand.feature` is a test skeleton that needs to be fleshed out. 

These is a comment that is useful, in addition to the test skeleton info in the file:
For line 6: It's actually to the PDF attachment page, not the final page. Right now the final page is the resource page. That may change if we add something to help people with SMS reminders, so I think checking that it's the PDF page may be best. (https://github.com/knod/docassemble-juvenilesealing/pull/25/files/99e5ae748410afb9b88126e0e1c61ebc77b30f1c#r349581251)

**Comment by knod** [comment]
Being handled in #49, but important info in here. Maybe move this info to #49?

**Comment by niharikasingh** [comment]
From @sperrys in #49, which is a duplicate of this ticket. 

> aloe test that asserts on the user flow after a user elects to finish the form by hand
> 
> After I am found to be eligible, if I click the "Finish by hand" button,
> I should be taken to the correct page.
> If I click continue on that page, I should be taken to the final page.
