### ISSUE TITLE
Present docket sheet info and instructions consistently to two paths of users

### ISSUE THREAD

**Issue by niharikasingh** [knod/docassemble-juvenilesealing#32]
On the question that asks if they have their docket sheet: If someone says "No" and next selects "I want to come back another time" for docket sheets, we should take them to instructions for obtaining their docket sheets before passing them on to the final page. Right now, these instructions appear when someone clicks "I don't know" on the docket sheets question. 

From @knod on 12/3

**Comment by knod** [comment]
Also, we want to edit the two docket sheet information pages so the visual description of a certified docket sheet is on the same page as the description of why docket sheets are important. (Right now it's on the instructions page). Also, both 'No's and 'I don't know's should lead to first the description page and then the instructions page.

**Comment by knod** [comment]
Also, we might want to think about where the 'about docket sheets' internal information link goes. Have to review that flow. Maybe offer a 'see how to get certified docket sheets' type button on that first informational page.

**Comment by knod** [comment]
Feel free to hit me up with questions about anything - logic, content locations, whatever else.

**Comment by niharikasingh** [comment]
> Also, we want to edit the two docket sheet information pages so the visual description of a certified docket sheet is on the same page as the description of why docket sheets are important. (Right now it's on the instructions page). Also, both 'No's and 'I don't know's should lead to first the description page and then the instructions page.

@knod I'm confused about which pages you are referring to above. Could you please let me know the IDs for these pages? That would help me resolve the ambiguity. For example, this page

<img width="730" alt="Screen Shot 2020-01-05 at 9 22 56 PM" src="https://user-images.githubusercontent.com/3387590/71791077-9ae4ae00-3001-11ea-8193-efe057a7954c.png">

with the code 

```
id: in_ma
question: ''
subquestion: |
  These questions are for sealing **Massachusetts** juvenile
  records. Do you have a juvenile record in Massachusetts?
yesnomaybe: has_ma_juv_record
```

would have the id `in_ma`.

**Comment by knod** [comment]
Good idea. IDs:
- The 'importance' page: docket_warning (juvenile-sealing-intro-10.yml)
- The instructions page: certified_copies_page_text_question (juvenile-sealing-text-10.yml)

They're named poorly and in different files for reasons that are probably no longer relevant. I fwe can change it, we'll do it as part of the restructuring.

**Comment by knod** [comment]
Also, if you can do this on v10, that would be ideal.
