### ISSUE TITLE
Should our 'fill out by hand' icon be a pen instead of a pencil?

### ISSUE THREAD

**Issue by knod** [knod/docassemble-juvenilesealing#40]
Since they shouldn't use a pencil. On the other hand, I'm not sure any of fontawesome's pen icons are very clearly a recognizable normal pen:
- https://fontawesome.com/icons/pen?style=solid (looks like it has an eraser)
- https://fontawesome.com/icons/pen-fancy?style=solid (not sure people will recognize what a fountain pen is)
- https://fontawesome.com/icons/pen-alt?style=solid (just looks weird and abstract to me)

**Comment by knod** [comment]
- The marker one (which is only available for pro accounts) looks pretty good, but we can't get it: https://fontawesome.com/icons/marker?style=regular
- There's also a signature thing: https://fontawesome.com/icons/signature?style=solid (not pro)

**Comment by knod** [comment]
Another option: https://fontawesome.com/icons/edit?style=regular

**Comment by knod** [comment]
But that may be too complex for good visual accessibility.

**Comment by niharikasingh** [comment]
We discussed this in the meeting, and decided the current icon is fine. Passed with three 5s @knod @berit @niharikasingh.
