### ISSUE TITLE
finish by hand UI tests 

### ISSUE THREAD

**Issue by sperrys** [knod/docassemble-juvenilesealing#49]
aloe test that asserts on the user flow after a user elects to finish the form by hand

After I am found to be eligible, if I click the "Finish by hand" button,
 I should be taken to the correct page.
 If I click continue on that page, I should be taken to the final page.

**Comment by knod** [comment]
First described in #29. Perhaps that information should be moved into here.

**Comment by niharikasingh** [comment]
Closing because duplicate of #29. I copied the relevant information there :)
