### ISSUE TITLE
Clarify button call-to-action

### ISSUE THREAD

**Issue by niharikasingh** [knod/docassemble-juvenilesealing#51]
In `docassemble/juvenilesealing/data/questions/juvenile-sealing-text-10.yml`, the `certified_copies_page_text_question` page has two buttons. We should tweak the text on this for readability. Not sure yet what the new text should be - that will need some UX feedback.

**Comment by knod** [comment]
For future notes, it's `docassemble/juvenilesealing/data/questions/juvenile-sealing-intro-10.yml`. The text is 'Yes, show me how to get my certified docket sheets'
