### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by niharikasingh** [knod/docassemble-juvenilesealing#53]
Delete `tests/README.md` and move its contents to the root `README.md`. 

Also restore the original contents of root `README.md`.

**Comment by knod** [comment]
Supposedly fixed in Docassemble core code! Changelog at 0.5.87 - 2020-02-02: https://docassemble.org/docs/changelog.html. I will try this out!

I think we might still want to include testing instructions on the main readme, but we can decide that later.
