### ISSUE TITLE
Document Aloe testing quirks

### ISSUE THREAD

**Issue by niharikasingh** [knod/docassemble-juvenilesealing#67]
- [ ] In `tests/features/finish_by_hand.feature`, we have to add spaces and icon characters to the end of the button text to get Aloe to find the right button. Document this at the top of the file 
- [ ] If we use ^ in any other file, document this quirk there too
- [ ] Clean up documentation at the top of `tests/features/ineligibility.feature`
- [ ] If using sentence like "Then I should see the phrase ...", the case of the phrase should be the same as the displayed case, not the same as in the HTML. 
- [ ] Right now, all tests run on `playground42` so if you want to test your own changes in your own Docassemble playground, you will need to change that. 
- [ ] Each scenario should have its own name. Scenarios with the same name will not be run. 
- [ ] There might be a race condition somewhere in the testing framework (either in `__init__.py` or `terrain.py`). The docket_sheets_link.feature test fails occasionally, possibly because it tries to read the text on the page before the page has fully loaded.

**Comment by berit** [comment]
I wonder if we can make changes to `terrain.py` to make the weird character quirks not a thing...

**Comment by berit** [comment]
Also at the moment you have to use Docker to run the aloe tests locally which is not the best

**Comment by berit** [comment]
Turning aloe tests into puppeteer tests so this is no longer relevant
