### ISSUE TITLE
Testing: When pushing and triggering a test, send the branch name with the test

### ISSUE THREAD

**Issue by knod** [knod/docassemble-juvenilesealing#85]
When you push to the repo (from wherever) you're on a branch. Puppeteer will need to know what branch you're pushing to so that the new project it creates can pull from that branch. Therefore we need to get github to send that information to puppeteer.

Alternatively, the dev changes .env to reflect the name of the branch they're pushing to.

Alternatively, we could create a hook that edits .env to include the name of the current branch, but that isn't as modular.

**Comment by berit** [comment]
We can probably do it using `github.ref`
https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

**Comment by berit** [comment]
Closed by #86
